apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-example
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/apoczekalewicz/openshift-applications.git
    path: example/resources
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: example-gitops
  syncPolicy:
    automated:
      selfHeal: true
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/sync: "true"
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:     
    - CreateNamespace=true 
