apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../resources

patchesJSON6902:
- target:
    group: ""
    version: v1
    kind: PersistentVolumeClaim
    name: persistent-app
  patch: |-
    - op: add
      path: /spec/storageClassName
      value: ocs-storagecluster-ceph-rbd
