apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  env: dev


resources:
- ../base

configMapGenerator:
- files:
  - envs/msg
  name: appconfig
images:
- name: quay.io/apoczeka/sample-app:latest
  newName: quay.io/apoczeka/sample-app
  newTag: 82ba90c459a6aea91e2f6071d0153eda17f9267d
