apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  env: dev


resources:
- ../base

configMapGenerator:
- files:
  - envs/msg
  name: appconfig
images:
- name: quay.io/apoczeka/sample-app:latest
  newName: quay.io/apoczeka/sample-app
  newTag: a930d36b6fb67bf7a71c035fa994501d40330cd1
