apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: persistent-app
  name: persistent-app
  namespace: persistent-app
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: persistent-app
