apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: persistent-app
  namespace: persistent-app
  labels:
    app: persistent-app
spec:
  clusterSelector:
    matchExpressions:
      - key: persistent-app
        operator: In
        values:
          - "true"
#  clusterReplicas: 1

