apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multiapp
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
           cluster.open-cluster-management.io/placement: multiapp
        requeueAfterSeconds: 180
  template:
    metadata:
      name: multiapp-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/apoczekalewicz/openshift-applications.git
        targetRevision: master
        path: sample-app/dev/
      destination:
        namespace: multiapp
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
