apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: etherpad-externaldb
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: etherpad-externaldb
              operator: In
              values:
                - "true"

