apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  app.kubernetes.io/instance: sample-app
  argocd.argoproj.io/sync-options: ServerSideApply=true
  argocd.argoproj.io/sync-options: Replace=true
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: sample-app
  template:
    metadata:
      labels:
        deployment: sample-app
    spec:
      containers:
      - name: the-container
        image: quay.io/apoczeka/sample-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: APPENV
          valueFrom:
            configMapKeyRef:
              name: appconfig
              key: msg
