apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.globalservicename }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}-pgpool
  ports:
  - name: pgpool-port
    protocol: TCP
    port: 5432
    targetPort: 5432
