apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
stringData:
  dbname: {{ .Values.dbname }}
  dbuser: {{ .Values.dbuser }}
  dbpass: {{ .Values.dbpass }}
  dbadminuser: {{ .Values.dbadminuser }}
  dbadminpass: {{ .Values.dbadminpass }}

  repmgr_password: {{ .Values.repmgr_password }}
  pgpool_postgres_password: {{ .Values.pgpool_postgres_password }}