apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: example-acm
  name: example-acm
  namespace: example-acm
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: example-acm
