apiVersion: v1
kind: Namespace
metadata:
  name: example-acm
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  namespace: example-acm
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: example/resources
  labels:
    app: example-acm
  name: example-acm
spec:
    channel: example-acm-ch/example-acm
    placement:
      placementRef:
        kind: PlacementRule
        name: example-acm
