apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: quay-creds
spec:
  encryptedData:
    password: AgDLjRSOhrlJ+O/VGguejyeGGdMSixGHKYyIZojmZMA4Z1Vvn3PRjDSwdQ1+g3M9yVC5y1SfJ5BCwyRt5pcepXOe0MYPuq1B+cuNHlqQa2M7GXj7XcWqeu46SkMbSD7T7cR9ct0FkiVDVYun6ll5OrL2vhPzk1xdSZRswYehnhED188LCJTXY+kUP3EB4CjuGQOXSuQZS1j3M6AMO2CC/9tiSOc8vU2L1Sz20HC2VyKoAhkxJhwy7UpFexpUtlSz4Yyncwq1oWjX8mwpQMLymKL9gaRwfmARb8O7Ey2axeS4Q0SFsS+3U7ASLwBLaqHJZvUyytGrIomeeW2yGhES4o+EE4NyHmAGUoxXQPr2Xf/K/7M0DpvOz0/PGFbG6Jg2GKo0oVNTDuxLi2Mr7sq8cC6OarL2AXG2J1ccKgMGo5HJhhs+mKKW3eTk5eL6X/WBA02zZgHRHJEgaVlii3gucxc3Bh7s2QoBVwk9AzewcnHJORz+NwpNNRqn1u+AooulNwTV3YMrtUDMNcvvAHYGDQ0RC4cyl13OeXz3d160+tIF1QjO7tOD6KMgsOfK9qSG6buKb9kT1hzteO6TgarnltBB6xkJ9Hc7/rkQthFtCW5JoDcTnMwR1nya08wspHZP95+pO0+JoxK2zrmbnbV7zqhTnrLJU/3LLANEqBYJbohGgfh5WiidcfBSHLpBeaNFLsgverP5FgkZ2wlLJg==
    username: AgCFTmCagQ5ZYC9vDOMt6tx0m9DFdhCbCjNFxmiDeYNaI3cxR6LGX+OLNd21D6NOpG6zMWndXlU2+rO+Bsebw4nDbuiWlzstNlUDpNSvcjgu+2y7a70DNRrM8eOp8tpXkXErARMpNhEd1P/Z4yBgRGc5Rm1X1qBAZtouAwmk7jnFeITXHRY9QuqxqibGnUpPXNBgkvEvs6HQxO9dblexyN/JCj3QALbcqtbQT4nXvnOd2v+/OjnzPF7ZjX6s37DWl7alqNz1JACXaXTOs9+t/V6g/APoUK61XpkqMIY0GUMD0kGd5aul4Wg3QvMFYyXpFUJCHEyirDRmPtu30YjiGydcPtLf7he4i+o8rXpvock7x0IEL2XLsYaq1BxbYkHEAMeBjrrf/7NqQ7WYTptqd3yX1aNsbStdhXgu6RCCvTjhCD4Z9p8OOuf1GhMqi6AMlgpDoC7Sk3RoWtmSYVIviQdVtDVT5DunaQSLoT7JeKBkdlwXIckiuyw6oO6B+puCvRkvvqux2ew7F3ob/RJpcC2ZTtxSER3ifRwmfWdEykT4TdNsGUBTcP76QmEuOJJDviH/t6M0S1psiJHUYuegdhi1QEuv/umzpfhb2BI5pUBA0EOWoDCxhhmS2lTeWIiq1eKglFq92auDDebP7KavJW5G3tkqkC/FeZdDtJpStULl4GGj/kAs4mow1xHXbISTrhMoAD02vGhlLqW2pafYB/8hSBrI
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/docker-0: https://quay.io
      creationTimestamp: null
      name: quay-creds
    type: kubernetes.io/basic-auth

