apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: argocd-env-secret
spec:
  encryptedData:
    password: AgCjGooz6quOSNw8lVjCPUu/Igb00YLGq8LYUr0WrpOuuwDxCWpj+tOsSjEzaAHR/SMTQuQP3SDbbYqDuHDJkJndTUbg9l48M5KX1vw3bd6bqMx6qryXBMXOJ9IT+SEDyf6YkM8nH3VeOk8xyjUmUNiai/xnoHUf5TNh1dttnl0+dblnlXj9qa23ZBX4Fkhx5U4TxeXMBXHmVr9frdDWsC7JJa0O5uG6/miYfnSKygo38MF03ivyhnbecRvgoEwYH+VuNVFNuHVm/baIcXIfAFYVbh7Hok+cUB7z0wOJfTz5MHRTg/XT5vPsT/lko5knCzjIrV5v5u7IFnnpDs5WfnZuZUHgY+Aczw/Tp2uCuHZrt8OKwQV56ZwyWeUPqaGfajjs2erjaO6dBJzs45ul1hVY7oDXgdSiwf0GNGUM1QQCv6XfKqpIiO7+M2LVn2XOoks5JIcT04ZhLWjCfRymL7Cip4TYh6jn87KVWOuVcLugI7JfO+pHRYPOmYw88bJp+Tp0xyxRWxk+srneOJo7ud7QPHxDlvAkNv1L9yhxEsjlkI6hWFBSeJa3i4pnG9WlJFVOh6qcd0D6HhWiY7j630VpyYue+HKmum0ybkWQVp0/vBkfdqSKMhxuB1LTGlfHCWf3f+kWjaZbOhewvbQamlLdKl1lSXwtiD383k9fRlLCt7tL2E6XVglVbWNJyIb+slYnJlmxI1DJwA==
    username: AgC09ewe3fWD9jIvuPZOSQSY81US+G2YDgWb48PBxd1ef6n8X/xrvBI2urIcsy9QvtaxsBL1+kVMyKp2MgJ0fjNSw3bJfr7s7N68hjnd5myGKV01gH7txFfQDFZnoZIy5QY06sc1sFXH68qaVlR1DQNR9gXDqPHywEmvdTg70Lco6f0x5ItTsKTACXRjRAYnxVfxTTsJQZubr3EZTLgBQrZUMXR8+bQDS/+WZtlK4C3KSelykaALRP4utHe6OIZZQ1kNHLppwHfemB+MU/ween07cKhlbkmvmuKIOfrllOgkLY34zDWzQyxAlmSZlx+xgMmdBKbDx06I/ylauQpW02uSTVUeBN1Oz//i8TaKWbDNbOKFsrZhOJPhNI3oZdBIHyIDcC075ztwr9h3FZNNHsiRlX+lTcogKO12AsN1+Z8Fk1KSqhMzMqN6n/3VVhl4ZXsoCCWoyJxI087xAElk+JHsOut2SVvZiDf/wcaoMO8c7V7GF6jWd0hwlOqQ7HSLhfpG/8QSem3QxheMRJXhTBIzOr7d0WJkQcU5YGhDm+N9RNdu9edqdI3KxKoqK81VNzxVQXoAl8o4gtmVsAnWIvzhxuIMbecQ+6rGZHL4KX3BqhDgAmGFHVARkgffsys9QmjXdkXE92TjwCEZq2CM8ZDgtynAI3wISwf+8u86mzCUX43wVXTYy8CHRHDdJE1n05a3Of/rbA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: argocd-env-secret
    type: Opaque

