apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: allure-auth
spec:
  encryptedData:
    password: AgCdtBGFArQqSYP1viHI6jUTZVOkBtaj4jYUrHoZoj2K7bnJlCECyPlHeYU1HI2QkNN6OYJura1tQK/E0+cSxycEHFu07vLQzMrUgwO1WELLQKdnpN5dY8nghzorQNgf97GeA6oFLSRYG9/1mbB2MVAWa9+9v3p8LY3clYBhyrU+7AGOPTPo6Fib2JGzYpyNdvzKl7djyGEy8Zl1bTrAvp2PG3DEFLMeyr1+HQRKdkKMl3TnEu0uLaKmD6pG9um1jTJ64jrE7EaRLnj7Pk7sJ66V8FVp2+1y6BvM15cunalTG/emlMGQl7nGQWkEIJq3P7EoJoYIPXFfoqdLbR/+k+GE0vgl7F5E10zwILyaxNCUX7SsJOTdusUplMNbthliS0I78YKrM+xE7e8G4i/rSEM7jeGK34bcndGm+XfTlPSjO2DYVlwB9D5EwzsdBuG3P/b/5l+Uxuyn98+bUVS7hVsTA3v+TAuNe2R2HlK6zsne0LsN4OXyyd/hLkYlVjI88sKwX0N51bev4GcgO3sW1RKGD7RfJVEaDYrnixmvyW5FEKXY/E1kUzsDF7+kNRQ7AfgjIs81cfFKZbdV6ukKueH/1UTbJvcXWINto95GXR9WFlhxPm3BfnSG9RqXn7ZGi5CUkrk68y3q4JBOHSzNWUn76vn8LBZThJL9uQ7SNezyPiho3YvEertV1P7B+jg0HwiR3x+4OJrOIQ==
    username: AgCMGpQOjAtEHJezmoJTFQZDr6TPNFx0pAQ8sWmYfdg5rmlk/3Xld8wMMqIAj4Er3mc8kCteKuTQPpelvs6d2d5K8vcC9cebsZtsm9PqOG6iffdAzGsa/cSdyqVcXih4sfCX+HN9Yuu2IJC6kx8HicdEdmeABzNMKyM0v2UVUGi4QAR6G9bnZi+JoBkllQbAl87B30TWwGJQHv6z17JgmOqKrk/Bu9MSa3TzD+xCVbAr/pzdjO1f/jt5TKS0q/ygs1Qo+TcJtQQV9uE/dEMFxab2nY6IFSeb6svmxNcfC6xurIlX0TINxE62u9/VvnMCOwkkUKdGwiZJNjmt4I1CCbXmXAdwGr+QJG2gZBlRbygq3y2qqy9BW8zrejXzn4vTLz/smIisY2nWy3UlUgSKHvpgmWJ7VEN8EzlvS17btuMa0LzZ08GQo4oUHNUVQHQNyUNj9s11mwuSGCIfz15sfAVeceejKDsxvW6K7UbvVdHfqN5td8sOvxWzP7uusWYHYCpOnW5rYRHD6XpOVUO+0dt2GwEVoF5xD5lJ/rog5jU99ZnbXvx07Oi2ogBg1LztwIgWrfVp83RNbEmRBSm2wFKdnNRgXduBQjTSn4S8W+U5t0xIumT08oUtCvN1QiMNLk9tusejL4+tLnHfbZhS+w2FKUVouZ94RUC0i79bcaLfz7w9YHa2lyZw0rdr2cEqTvixBu5Dig==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: allure-auth
    type: Opaque

