apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: quay-creds
  namespace: sample-app-cicd
spec:
  encryptedData:
    password: AgAe47S2TaJkP8wjDIHrsTgTlsTFBPNJwo/Koh5rbbBOm4uAlCZBegxq0JiPLqJwB+uo00vpWhdpl4+C7uJiEdkITyaeMXIv4vf2tIOug1LFtLQJ64DvKhAR/pjgLaXu/t20FMDIrc98UdXNfdv4ioG6vjcnaykbgW0K6XBJRxKRE8ZLoi83V7l1bKdJxfed4JgLInIXzPpiGa5w6IeR9iB5NlJjakmSXXFXUWugKgQ5cgnKQgggxuJ/iyAB1xHq4v+cFZ32kCQzPzEU0yU7xfgdbalte6k8BiDEikiHe4Wl+JagF5nRGeEBlLYSPKx/hqEr4L5I+9LYomXpdwnvwqedHob4q1eK9vklGqZ5gwT7CqEWkPYuXzbFp0zeBnnT9L8Aq67uqXhAFt+LS8bqS12clZWb0VN2vwlHb7hCLICmbW4bMeBzePPR35HveqwWtA+pRURDvo+NJmyAAqSHShrdvTGqXLNQ39n6moECYLXu0zsn2OkSp7XTxtIpwQPuykniyWX+xnWkte7GCqKGrnf2HDQxXTKrlldKYCae94O1tkSFhAot08/r7XNaQJlbpkxpyWKp3gcgvUWyIgSSnoFyBOLgUd6tp3FL5HQ7uCPLF1GZtcfHrxIyLPohm4AcloSIsJJb2/MuuMG+7eLyHfUfj3D491E1C2+LUXNxt4qtmCcGdrn1RhaMyow+slIaGAVjgplnGTnhBs705A==
    username: AgCtSEhVPzoiBUgpJucPNu3QokEBwLxHP7czRGOhuc5BDBFRIT7Hop31DWla068gO54cJQ9HMe4OqUoeHgqYvE9WpCOB5Wx0eQeER3tzm2rPH18JrraYVEbBtbM7ftggo0xY5+WobgJYzvrgE/aS7gVsEhkGO4FgK1yGvseIv7QEb+r0iTEPcJSOOBjQ/E6ZlJUshgaB/VFIMwq/Jd6mjdtW9nGDS4VAVW6hVFRzSX+zOHctCX4j5URYGM8kMYaD46tvEQgVZpARk3toIvMtmVMurQhmdlxorblT3fUO749Y/dfV63cr9NEu5658mw6DVt7K+NRtaKoXyoGYe+gXeYqhbiflEjHgFIrYovtURKk6vcEvjhxgx83FU+HX9OQaVa3Qv92C78+Bf/20fX2e+1oZ7EWZAM8eOKn/xVPPpM+uMFMQy4Knw0htmiG8rKQSA87zwCrvR9SnVJniPdlXKCBY3MvHzpo0PuJHrh9fNaiJhnZiEkCpVL25ni4H6ir0vNcz/m730b+zJOWx6m81w38n0wte3MIwjnITZLaomAImE85PnmFfJpVvdb70IpvCSZHq/PH4fE7qayyl9Ddas4oIfcW2vbvvSCZIMxVyh0wGUd8ANItp6ON7CFBIq0JEEpVrI8Cpzmt3msCEXdKE+pBfWqDI9rloKp6NSoSIyj0xtf5s+QY/TQFq6cyH4FPWoQnqmj805wlh92QDY7R6CVEojUzy
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/docker-0: https://quay.io
      creationTimestamp: null
      name: quay-creds
      namespace: sample-app-cicd
    type: kubernetes.io/basic-auth

