apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: sonarcloud
spec:
  applicationMenu:
    imageURL: https://pbs.twimg.com/media/DCR6TNyW0AQdLig.jpg
    section: Security - applications
  href: https://sonarcloud.io/projects
  location: ApplicationMenu
  text: SonarCloud

