apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: etherpad
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
           cluster.open-cluster-management.io/placement: etherpad-externaldb
        requeueAfterSeconds: 2
  template:
    metadata:
      name: etherpad-externaldb-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/apoczekalewicz/openshift-applications.git
        targetRevision: master
        path: etherpad-externaldb/resources
      destination:
        namespace: etherpad-externaldb
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
