apiVersion: v1
kind: Secret
metadata:
  name: database-secret
stringData:
  database-name: database
  database-user: user
  database-password: password
  database-host: postgresql.database.svc.cluster.local
  database-port: "5432"
