apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresql-sa
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: postgresql-scc
subjects:
  - kind: ServiceAccount
    name: postgresql-sa
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:postgresql-scc
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:postgresql-scc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - postgresql-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: postgresql-scc
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
priority: null
readOnlyRootFilesystem: false
#requiredDropCapabilities: 
#- KILL
#- MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- hostPath
- persistentVolumeClaim
- projected
- secret

